services:
  php-server:
    build: .
    environment:
      - TZ=Europe/Lisbon
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BD_associacao
      TZ: Europe/Lisbon
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./Database/associacaomusical.sql:/docker-entrypoint-initdb.d/01-associacaomusical.sql:ro
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      TZ: Europe/Lisbon
    depends_on:
      - db
    restart: always

volumes:
  db_data: